[colors]
background = #1e1e2e
foreground = #cdd6f4
primary = #89b4fa
secondary = #f5e0dc
alert = #f38ba8

[bar/mybar]
width = 100%
height = 30
radius = 8
fixed-center = true

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3
border-size = 4
border-color = #00000000

padding-left = 2
padding-right = 2

module-margin-left = 1
module-margin-right = 2

font-0 = monospace:pixelsize=10;2
font-1 = "JetBrainsMono Nerd Font:style=Regular:size=10;2"
font-2 = "Font Awesome 6 Free:style=Solid:size=10;2"
font-3 = "Font Awesome 6 Brands:size=10;2"
font-4 = "Symbols Nerd Font:size=10;2"

modules-left = gentoo-drawer i3
enable-ipc = true
modules-center = date
modules-right = cpu memory battery pulseaudio

monitor = ${env:MONITOR:}

[module/i3]
type = internal/i3

# This keeps the workspaces locked to only showing 5 slots
pin-workspaces = true
show-urgent = true
strip-workspaces = true

# Style for the active workspace you are currently on
label-focused = %index%
label-focused-foreground = #ffffff
label-focused-background = #bb9af7
label-focused-padding = 2

# Style for the other inactive workspaces
label-unfocused = %index%
label-unfocused-foreground = #565f89
label-unfocused-padding = 2

# Style for empty workspaces
label-visible = %index%
label-visible-padding = 2

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = " "
format-prefix-foreground = #9ece6a
label = %percentage%%

[module/memory]
type = internal/memory
interval = 2
format-prefix = " "
format-prefix-foreground = #7aa2f7
label = %percentage_used%%

[module/battery]
type = internal/battery
full-at = 99
low-at = 5
battery = BAT0
adapter = AC
poll-interval = 5
format-charging = <label-charging>
format-discharging = <label-discharging>
label-charging = "󱐋   %percentage%%"
label-discharging = "  %percentage%%"

[module/pulseaudio]
type = internal/pulseaudio
format-volume-prefix = "󰕾 "
format-volume-prefix-foreground = #bb9af7
format-volume = <label-volume>
label-volume = %percentage%%
label-muted = 󰝟 muted
label-muted-foreground = #707880

[module/date]
type = internal/date
interval = 1
date = %Y-%m-%d %H:%M:%S
label = %date%

[module/gentoo-drawer]
type = custom/text

# The beautiful Gentoo Logo (Uses your Nerd Font!)
content = " 󰣨 "
content-foreground = #bb9af7
content-background = #1a1b26
content-padding = 1

# When you click the Gentoo logo, it sends a command to toggle the workspaces
click-left = ~/toggle_workspaces.sh &
